apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: storagepersistente-sa-east-1c
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi