apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: br-common-qa
type: Opaque
data:
# echo -n 'brq_postgres_2023' | base64
  POSTGRESQL_ADMIN_PASSWORD: YnJxX3Bvc3RncmVzXzIwMjM=
  # echo -n 'brq_sonarqube_2023' | base64
  POSTGRESQL_PASSWORD: YnJxX3NvbmFycXViZV8yMDIz
stringData:
  POSTGRESQL_DATABASE: sonarqube
  POSTGRESQL_USER: sonarqube
  PGDATA: /var/lib/pgsql/data/pgdata