apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresql
  namespace: database
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /workspace/postgresql