apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgresql
  namespace: database
spec:
  volumeName: pv-postgresql
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi