apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: database
type: Opaque
data:
  # echo -n 'paschualetto' | base64
  POSTGRES_ADMIN_PASSWORD: cGFzY2h1YWxldHRv
  # echo -n 'ferfernando' | base64
  POSTGRES_PASSWORD: ZmVyZmVybmFuZG8=
stringData:
  POSTGRES_DATABASE: postgres
  POSTGRES_USER: postgres
  PGDATA: /var/lib/postgresql/data