apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sonarqube
  namespace: sonarqube
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /workspace/sonarqube