apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-secret
  namespace: br-common-qa
type: Opaque
data:
  # echo -n 'brq_sonarqube_2023' | base64
  # squ_661718b8e3377f238e3ff3a3e4f0d6b509427141
  SONARQUBE_JDBC_PASSWORD: YnJxX3NvbmFycXViZV8yMDIz
stringData:
  SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonarqube"
  SONARQUBE_JDBC_USERNAME: sonarqube