apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-secret
  namespace: br-common-qa
type: Opaque
data:
  # echo -n 'paschualetto' | base64
  SONARQUBE_JDBC_PASSWORD: cGFzY2h1YWxldHRv
stringData:
  SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonarqube"
  SONARQUBE_JDBC_USERNAME: sonarqube