apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: database
spec:
  type: NodePort
  ports:
  - nodePort: 32761
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: adminer
  sessionAffinity: None